### ISSUE TITLE
AWS Integrations

### ISSUE THREAD

**Issue by jwoertink** [crystal-community/crystal-libraries-needed#31]
abstracted from #9

Since AWS is so large, would we want to see 1 massive AWS library, or a series of smaller AWS shards? I personally think the latter. I'd like to see `crystal-aws/aws-s3`, `crystal-aws/aws-rds`, etc...

**Comment by johnjansen** [comment]
i would suggest one core / common shard, then shards for each service ...

**Comment by fridgerator** [comment]
It would be cool to see crystal on this list: https://aws.amazon.com/tools/

It appears though, that all of the SKD's are maintained by AWS with the exception of the Python boto library.

I wonder if there are any considerations that would need to be followed before they would list it.

**Comment by johnjansen** [comment]
@fridgerator totally agree, although we need to create something before getting it listed ;-) ... hands up who wants to manage this ticket :-)

**Comment by fridgerator** [comment]
If the human body didn't require sleep, I would totally volunteer to help with this 😆

**Comment by johnjansen** [comment]
oh boy do i know what you mean

**Comment by RX14** [comment]
I don't think seperate shards are really required, it's easier to maintain and keep the interface consistent working in 1 repo. And having unused methods has little effect on compile times

**Comment by johnjansen** [comment]
@RX14 its really only a practical consideration, we arent going to be able to deliver a complete shard at this time (or probably anytime soon), so if we can break it up and get each bit feature complete and tested then we can combine them at a later date

**Comment by RX14** [comment]
@johnjansen I don't really see why incremental PRs can't be landed in a shared repository.

**Comment by elorest** [comment]
Personally as long as we have an API a wrapper probably isn't really needed at this point. For instance if we wrote a carrierwave alternative we could just build in the parts we needed to interface with the api then. Eventually it would probably be useful but my experience from ruby is that using a gem wrapper often isn't easier than just hitting the api and you only need to read one set of docs that way.

**Comment by molovo** [comment]
I'd vote for smaller shards, so that the specific parts of the API can be used by other packages easily, without having to require a huge monorepo. For example, a simple S3 integration could be used as part of something like [Flysystem](https://github.com/thephpleague/flysystem) which I would love to see in Crystal.

**Comment by johnjansen** [comment]
agreed @molovo ...

**Comment by RX14** [comment]
What is the problem with requiring a large shard? It will all live under 1 namespace so there's no more namespace pollution and it should have practically no impact on compile times. A large amount of the standard library is required in every crystal program but what effects compile times is the amount of that required API surface you use.

However, the benefits of using a monorepo (easier to maintain and keep internally consistent) seem clear to me. Even as a user i'd much rather require "aws" instead of each individual service I use.

**Comment by johnjansen** [comment]
understood @RX14, it may well wind up that way ... im only 1 vote, if however someone wants to write an AWS signer, and someone else wants to write a fully S3 implementation (which i think is the likely course of events) im not inclined to force people into a collaboration and decision by commitee if you follow my logic ... not that im in any position to do any forcing, just to be clear ;-)

**Comment by fridgerator** [comment]
one problem right now, is when trying to access AWS api on MAC, I always get this error:  Anyone else get this?

`<?xml version="1.0" encoding="UTF-8"?><Error><Code>HttpVersionNotSupported</Code><Message>The HTTP version specified is not supported.</Message><RequestId>2750C2CAA689256F</RequestId><HostId>xxxx</HostId></Error>`

I'm using this right now: https://github.com/taylorfinnell/awscr-signer

I'm just assuming regardless of the shard, this error will persist

**Comment by jwoertink** [comment]
@fridgerator How are the filenames formatted? Might need to url-encode them before uploading.

**Comment by fridgerator** [comment]
Oh sorry, this is retrieving a signed url for a file from S3 using `HTTP::Client`

**Comment by timkendall** [comment]
Might be good to have all of the AWS libraries in one place as well (at least until AWS officially supports and perhaps takes it over). Maybe in the **crystal-community** GitHub org or a new **crystal-aws** org.

Making all of AWS readily available in high-quality shards is definitely something that will push the Crystal community forward. So many people depend on AWS for their daily jobs.

**Comment by omerxx** [comment]
Hi guys, any progress with the AWS shard? 
Is there a progress going on somewhere? Would love to take part.

**Comment by jwoertink** [comment]
@omerxx I don't think so. You can find some here http://crystalshards.xyz/?filter=aws. I'm using some AWS stuff in my projects, but none of it has been abstracted to a shard yet.

**Comment by findchris** [comment]
Stumbled across: https://github.com/sdogruyol/aws

**Comment by jwoertink** [comment]
Yeah, I think this can be closed. There's a few options out there now for some basic stuff.
