### ISSUE TITLE
Authorization framework

### ISSUE THREAD

**Issue by johnjansen** [crystal-community/crystal-libraries-needed#4]
something like CanCan or Pundit for Ruby

**Comment by elorest** [comment]
I believe that Warden is an Authentication framework. https://github.com/hassox/warden

Although I do think it might be cool to have authentication and authorization tied together. I've been meaning to port over https://github.com/elorest/petergate to crystal as soon as myself or someone else makes a complete authentication solution.

**Comment by bigtunacan** [comment]
@elorest is correct.  Warden is an authentication framework middleware for Rack.  Then Devise is layered on top of Warden.

Pundit (https://github.com/elabs/pundit) and cancancan (https://github.com/CanCanCommunity/cancancan) are the two main authorization framework options in Ruby.

**Comment by johnjansen** [comment]
yeah, i realized that afterwards, sorry it took me a couple of days to update ... too much on my plate

**Comment by ilanusse** [comment]
Here's my small authorization library inspired by Pundit: https://github.com/ilanusse/praetorian

Hope it helps! Feel free to add enhancements as features.
