### ISSUE TITLE
Git Wrapper 

### ISSUE THREAD

**Issue by marceloboeira** [crystal-community/crystal-libraries-needed#41]
A lib to create/manipulate git repos with crystal.

I am not sure if using directly system calls or libgit bindings... but anyway, I have started a while back: https://github.com/marceloboeira/git.cr

**Comment by RX14** [comment]
This project seems active: https://github.com/mosop/git

**Comment by marceloboeira** [comment]
@RX14 true!

**Comment by bararchy** [comment]
Can this be closed then ? (also http://crystalshards.xyz/?filter=git)

**Comment by Nephos** [comment]
The mosop's work is far from finished and the other shards are not good.

**Comment by RX14** [comment]
If it's not finished, perhaps send a PR with the functionality you want. Starting from scratch is usually a bad idea.

**Comment by Nephos** [comment]
looks like it's dead...
I feel bad for it because it could be so useful but the documentation a hell

**Comment by icyleaf** [comment]
Maybe the author of libgit2 gave up with Crystal:  https://twitter.com/moso2p/status/889456195014082560

**Comment by Nephos** [comment]
I can't read this!

Is someone confortable with libgit2 ?

I tried last year, maybe I should try again with https://libgit2.org/docs/guides/101-samples/ ?

**Comment by alexanderadam** [comment]
[libgit2.cr](https://github.com/smacker/libgit2.cr#libgit2cr) seems quite maintained.

**Comment by Sija** [comment]
It does seem a bit incomplete though - and I mean the important parts like `Remote.fetch`.

**Comment by alexanderadam** [comment]
> It does seem a bit incomplete though

Yes it does.
But this isn't an issue for the `crystal-libraries-needed` repo then. It would be an issue (or PR) on the shard repo, wouldn't it? :thinking:

**Comment by Sija** [comment]
@alexanderadam Fair point, closing!
