### ISSUE TITLE
Cairo bindings - generic drawing library

### ISSUE THREAD

**Issue by bew** [crystal-community/crystal-libraries-needed#54]
> From the main website:

Cairo is a 2D graphics library with support for multiple output devices. Currently supported output targets include the X Window System (via both Xlib and XCB), Quartz, Win32, image buffers, PostScript, PDF, and SVG file output. Experimental backends include OpenGL, BeOS, OS/2, and DirectFB.

Cairo is designed to produce consistent output on all output media while taking advantage of display hardware acceleration when available (eg. through the X Render Extension).

The cairo API provides operations similar to the drawing operators of PostScript and PDF. Operations in cairo including stroking and filling cubic Bézier splines, transforming and compositing translucent images, and antialiased text rendering. All drawing operations can be transformed by any affine transformation (scale, rotation, shear, etc.)

Cairo is implemented as a library written in the C programming language, but bindings are available for several different programming languages.

---

Manual: https://www.cairographics.org/manual/
Notes for bindings: https://www.cairographics.org/manual/language-bindings.html

Ideas from rust bindings (for the documentation): http://gtk-rs.org/docs/cairo/

**Comment by TamasSzekeres** [comment]
Here it is https://github.com/TamasSzekeres/cairo-cr

**Comment by bew** [comment]
@TamasSzekeres nice simple bindings!

But it still feel writing C, I'd prefer to have a Crystal wrapper for each logical objects like `Cairo::Context` or `Cairo::Surface`, and be able to call methods on them:
```cr
my_surface.draw do |ctx|
  ctx.rectangle(0, 0, 20, 10)
  ctx.fill
  # or directly: ctx.rectangle(0, 0, 20, 10).fill
end
```
But that's for sure another piece of work!

**Comment by alexanderadam** [comment]
@Sija this can be closed then, right?
