### ISSUE TITLE
JavaScript execution library

### ISSUE THREAD

**Issue by watzon** [crystal-community/crystal-libraries-needed#60]
Something like [execjs](https://github.com/rails/execjs) that would allow the execution of Javascript code within crystal using something like [Duktape(http://duktape.org)

**Comment by RX14** [comment]
there's already duktape bindings (they look really nice and well-featured actually) https://github.com/jessedoyle/duktape.cr.

**Comment by bararchy** [comment]
So.. can this be closed ? as we have a lib for that
